send_key:
  description: Sends key press to media player.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: "media_player.tv"
    key:
      description: Keycode to send
      example: "prog+"
send_command:
  description: Sends custom commands to media player.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: "media_player.tv"
    command:
      description: Command to send
      example: "SETMUTE"
